version: "3"
services:
  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mcc_admin
      POSTGRES_PASSWORD: mcc12345
      POSTGRES_DB: mccdb
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
